config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :data_entries, only: %i[new create]

  namespace :api do
    namespace :v1 do
      resources :data_entries
      resources :users, only: [:index]
      devise_scope :user do
        post '/tokens', to: 'tokens#create'
        post '/register', to: 'registrations#create'
        delete '/tokens', to: 'tokens#destroy'
      end
    end

    namespace :v2 do
      resources :data_entries
      resources :users, only: [:index]
      devise_scope :user do
        post '/tokens', to: 'tokens#create'
        delete '/tokens', to: 'tokens#destroy'
      end
    end
  end

  get '/step-one', to: 'react#index'
  get '/step-two', to: 'react#index'
  get '/step-three', to: 'react#index'

  get '/trees/step-one', to: 'react#index'
  get '/trees/step-two', to: 'react#index'
  get '/trees/step-three', to: 'react#index'
  get '/trees', to: 'react#index'

  # get '/login', to: 'react#index'
  # get '/register', to: 'react#index'

  root 'react#index'

  match '*all', controller: 'application', action: 'cors_preflight_check', via: [:options]

  # match '*path', to: 'react#index', via: :all
end

app/models/data_entry.rb
# Abstracts data entry database table
class DataEntry < ApplicationRecord
  include Rails.application.routes.url_helpers
  include ActiveStorageSupport::SupportForBase64

  has_one_base64_attached :image
  has_one_base64_attached :secondary_image

  scope :with_image_urls_near_expiry, lambda {
    where('image_storage_url_expiry_date <= ?', expiry_date)
  }

  def self.expiry_date
    Date.today + 6.days
  end

  def self.refresh_stale_image_storage_urls
    with_image_urls_near_expiry.each(&:save_image_storage_url!)
  end

  # NOTE: local file path rails_blob_path(image)
  def image_url
    return unless image.attached?

    image.variant(auto_orient: true).processed.service_url
  end

  def secondary_image_url
    return unless secondary_image.attached?

    secondary_image.variant(auto_orient: true).processed.service_url
  end

  def save_image_storage_url!
    if image_url
      update_columns(image_storage_url: image_url,
                     image_storage_url_expiry_date: DataEntry.expiry_date)
    else
      update_columns(image_storage_url: nil,
                     image_storage_url_expiry_date: nil)
    end
  end
end

app/controllers/api/v1/data_entries_controller.rb
module API
  module V1
    # API controller for data entries
    class DataEntriesController < MainController
      # GET /notes
      def index
        @data_entries = DataEntry.all

        render jsonapi: @data_entries
      end

      # POST /notes
      def create
        @data_entry = DataEntry.new(data_entry_params)

        # rubocop:disable Style/RescueStandardError
        begin
          # NOTE: This is a hack to get around an issue with S3 images saving
          # and timing issues with the after_save callback.
          @data_entry.save!
          @data_entry.save_image_storage_url!

          render jsonapi: @data_entry, status: :created
        rescue
          render jsonapi_errors: @data_entry.errors, status: :unprocessable_entity
        end
        # rubocop:enable Style/RescueStandardError
      end

      private

      # Only allow a trusted parameter "white list" through.
      def data_entry_params
        params.require(:data_entry).permit(
          :image,
          :secondary_image,
          :latitude,
          :longitude,
          :notes,
          :subtitle,
          :title,
          :username
        )
      end
    end
  end
end

app/controllers/api/v2/data_entries_controller.rb
module API
  module V2
    # API controller for data entries
    class DataEntriesController < MainController
      # GET /data_entries
      def index
        @data_entries = DataEntry.all

        render jsonapi: @data_entries
      end

      # POST /data_entries
      def create
        set_data_entry

        # rubocop:disable Style/RescueStandardError
        begin
          # NOTE: This is a hack to get around an issue with S3 images saving and timing issues with the after_save.
          @data_entry.save!
          @data_entry.save_image_storage_url!
          render jsonapi: @data_entry, status: :created
        rescue
          render jsonapi_errors: @data_entry.errors, status: :unprocessable_entity
        end
        # rubocop:enable Style/RescueStandardError
      end

      def set_data_entry
        @data_entry = DataEntry.new(data_entry_params)

        primary_image = data_entry_params[:image]
        secondary_image = data_entry_params[:secondary_image]

        @data_entry.image.attach(data: primary_image) if primary_image
        @data_entry.secondary_image.attach(data: secondary_image) if secondary_image
      end

      private

      # Only allow a trusted parameter "allow list" through.
      def data_entry_params
        params.require(:data_entry).permit(
          :image,
          :secondary_image,
          :latitude,
          :longitude,
          :notes,
          :subtitle,
          :title,
          :username
        )
      end
    end
  end
end

app/controllers/data_entries_controller.rb
# Handles CRUD functionality for DataEntry records
class DataEntriesController < ApplicationController
  before_action :set_data_entry, only: %i[show edit update destroy]

  # GET /data_entries/new
  def new
    @data_entry = DataEntry.new
  end

  # POST /data_entries
  # POST /data_entries.json
  def create
    @data_entry = DataEntry.new(data_entry_params)

    respond_to do |format|
      if @data_entry.save
        format.html { redirect_to root_path, notice: 'Data entry was successfully created.' }
        format.json { render :show, status: :created, location: @data_entry }
      else
        format.html { render :new }
        format.json { render json: @data_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_data_entry
    @data_entry = DataEntry.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def data_entry_params
    params.require(:data_entry).permit(
      :image,
      :latitude,
      :longitude,
      :notes,
      :subtitle,
      :title,
      :username
    )
  end
end

app/views/data_entries/_form.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <%= form_with(model: data_entry, local: true) do |form| %>
    <% if data_entry.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(data_entry.errors.count, "error") %> prohibited this data_entry from being saved:</h2>

        <ul>
        <% data_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <h1>New Data Entry</h1>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :title %>
      </div>
      <div class="col-27">
        <%= form.text_field :title %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :subtitle %>
      </div>
      <div class="col-27">
        <%= form.text_field :subtitle %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :username %>
      </div>
      <div class="col-27">
        <%= form.text_field :username %>
      </div>
    </div>

    <div class="row">
      <div class="upload-button-wrapper">
        <button class="upload-button">Upload Image</button>
        <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
      </div>
    </div>

    <div class="row">
      <img id="image" />
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :latitude %>
      </div>
      <div class="col-27">
        <%= form.text_field :latitude %>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :longitude %>
      </div>
      <div class="col-27">
        <%= form.text_field :longitude %>
      </div>
    </div>

    <div class="row">
      <button id="get-coordinates" class="button" type="button">
        Get coordinates
      </button>
    </div>

    <div class="row">
      <div class="col-27">
        <iframe
          id="map-link"
          style="width:100%; height: 300px; display: inline-block; margin-top: 6px;"
          id="gmap_canvas"
          src="https://maps.google.com/maps?q=plymouth%20uk&t=k&z=13&ie=UTF8&iwloc=&output=embed"
          frameborder="0"
          scrolling="no"
          marginheight="0"
          marginwidth="0"></iframe>
      </div>
    </div>

    <div class="row">
      <div class="col-25">
        <%= form.label :notes %>
      </div>
      <div class="col-27">
        <%= form.text_area :notes %>
      </div>
    </div>

    <div class="row">
      <%= form.button 'Submit Data Entry', type: :submit, class: "button" %>
    </div>
  <% end %>
</div>

app/views/data_entries/new.html.erb
<%= render 'form', data_entry: @data_entry %>

app/views/data_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @data_entry.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @data_entry.longitude %>
</p>

<p>
  <strong>Title:</strong>
  <%= @data_entry.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @data_entry.subtitle %>
</p>

<p>
  <strong>Username:</strong>
  <%= @data_entry.username %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @data_entry.notes %>
</p>

<%= link_to 'Edit', edit_data_entry_path(@data_entry) %> |
<%= link_to 'Back', data_entries_path %>